### PR TITLE
Highlights brackets ('<' and '>') correctly.

### PR DESCRIPTION
**Pull request by ixti**
This is a re-based version of #52.
Closes #52.

### CODE REVIEW

**Comment by ixti** [comment]
@minad Please merge this. Seems like you was OK with this PR before ;))

**Comment by ixti** [comment]
Closing this due to no activity (I assume no interest as well) from maintainers side.

**Comment by minad** [comment]
@ixti Do you want to main this package? I am not a vim user.

**Comment by ixti** [comment]
@minad sure. will be happy to, I guess :D

**Comment by minad** [comment]
@ixti Cool! Welcome! I send you an invitation.

**Comment by ixti** [comment]
Thanks!

**Pull request closed without merging**
